name = "HMMBase"
uuid = "b2b3ca75-8444-5ffa-85e6-af70e2b64fe7"
authors = ["Maxime Mouchet <maxime.mouchet@imt-atlantique.fr>"]
version = "0.0.13"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = ">=0.2.0"

[targets]
test = ["Test", "Random"]
