name = "HMMBase"
uuid = "b2b3ca75-8444-5ffa-85e6-af70e2b64fe7"
authors = ["Maxime Mouchet <maxime.mouchet@imt-atlantique.fr>"]
version = "1.0.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ArgCheck = "1.0"
Clustering = "0.13"
Distributions = "0.20,0.21"
julia = "1.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
